version: "3"
services:
  yahoo-service:
    build: .
    image: yahoo-flask
    volumes:
      - .:/app
    # environment:
    #   - FLASK_APP=app.py
    ports:
      - "5000"
    labels:
      - "traefik.http.routers.yahoo.rule=Host(`www.my-site.test`)"
      - "traefik.http.routers.yahoo.tls=true"
    networks:
      - my-network
  
  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`monitor.my-site.test`)"
      - "traefik.http.routers.traefik.tls=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
